### ISSUE TITLE
Missing file - 'test.py'

### ISSUE THREAD

**Issue by saber-shi** [HongshengHu/source-inference-FL#1]
Note that the file 'test.py' is deleted, will it be uploaded again?

**Comment by HongshengHu** [comment]
> Note that the file 'test.py' is deleted, will it be uploaded again?

Thanks for your interest in our project. The 'test.py' is an empty file and uploaded by mistake. It will not influence the experiments so I delete it to avoid confusion.

**Comment by saber-shi** [comment]
However, the file 'mian_nn.py' can not compile since the imported 'test_fun' function from 'test.py' cannot be found.

**Comment by HongshengHu** [comment]
> However, the file 'mian_nn.py' can not compile since the imported 'test_fun' function from 'test.py' cannot be found.

Sorry for that, I have added the "test.py" file

**Comment by saber-shi** [comment]
It's okay now. Thanks for your kindly help!
